### PR TITLE
Added support for babylon parser

### PR DESCRIPTION
**Pull request by wardpeet**
Made some changes to support different ast providers. I only made it work with babylon and esprima.

We could add the options to make Line & commentLine dynamic as an option.
esprima says "line" and babylon "CommentLine" (but there are more differences)

### CODE REVIEW

**Comment by Kegsay** [comment]
Thanks for the work on this, but why should this project support multiple AST parsers? This PR adds a lot of complexity for questionable gains, so I would like some justifications first.

**Comment by wardpeet** [comment]
it doesn't have to :p but I wanted to support babylon to use spread operators and so on. I'm ok to ditch esprima and go for babylon.

**Comment by Kegsay** [comment]
I've thought about this and I don't really like the complexity this adds. It doesn't buy us anything. Spread operators will be / is supported in Esprima so I'd rather we used that. Sorry.

**Comment by Kegsay** [comment]
https://github.com/Kegsay/flow-jsdoc/issues/17 contains a concrete use case for **swapping** to Babylon (rather than support 2 parsers).

**Comment by wardpeet** [comment]
my intention was never to force 2 parsers. My intention was to allow more than 1 parser so I could use babylon instead of esprima and have all es2015/2016 features

**Pull request closed without merging**
